import './styles/Admin.css'
import { useMemo, useState, type ComponentType } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Activity, ArrowLeft, Bell, Brain, Building2, CheckCircle2, ChevronRight,
  Gauge, HeartPulse, Home, LogOut, Menu, Network, Settings,
  ShieldCheck, Upload, Users, X,
} from 'lucide-react'
import { Badge } from '../lib/shadcn/badge'
import { Button } from '../lib/shadcn/button'
import { Card, CardContent, CardHeader, CardTitle } from '../lib/shadcn/card'
import { Progress } from '../lib/shadcn/progress'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../lib/shadcn/table'
import { cn } from '../lib/shadcn/utils'

type Page = 'dashboard' | 'hospitals' | 'monitoring' | 'model' | 'performance' | 'users' | 'settings' | `hospitals:${string}`
type Status = 'Completed' | 'Training' | 'Offline'
type Tone = 'default' | 'blue' | 'green' | 'orange'
type Hospital = { id: string; name: string; status: Status; round: number; update: string; records: string; progress: number }

const hospitals: Hospital[] = [
  { id: 'HOSP-001', name: 'City Heart Hospital', status: 'Completed', round: 12, update: '2 min ago', records: '2,450', progress: 100 },
  { id: 'HOSP-002', name: 'Apollo Care Center', status: 'Training', round: 12, update: '1 min ago', records: '1,980', progress: 65 },
  { id: 'HOSP-003', name: 'Unity Medical', status: 'Completed', round: 12, update: '2 min ago', records: '3,120', progress: 100 },
  { id: 'HOSP-004', name: 'Green Valley Hospital', status: 'Training', round: 12, update: 'Just now', records: '1,760', progress: 48 },
  { id: 'HOSP-005', name: 'Metro Cardiac Institute', status: 'Completed', round: 11, update: '5 min ago', records: '2,870', progress: 100 },
  { id: 'HOSP-006', name: 'Central Health', status: 'Offline', round: 11, update: '1 hr ago', records: '1,430', progress: 0 },
]

const statusClass: Record<Status, string> = {
  Completed: 'bg-success/15 text-success', Training: 'bg-warning/15 text-warning', Offline: 'bg-destructive/15 text-destructive',
}

function StatusBadge({ status }: { status: Status }) { return <Badge className={cn('border-0 text-[10px]', statusClass[status])}>{status}</Badge> }

function Sidebar({ page, setPage, open, setOpen, onNotice }: { page: Page; setPage: (page: Page) => void; open: boolean; setOpen: (open: boolean) => void; onNotice: (message: string) => void }) {
  const navItems: { id: Exclude<Page, `hospitals:${string}`>; label: string; icon: ComponentType<{ className?: string }> }[] = [
    { id: 'dashboard', label: 'Dashboard', icon: Home }, { id: 'hospitals', label: 'Hospitals', icon: Building2 },
    { id: 'monitoring', label: 'FL Monitoring', icon: Network }, { id: 'model', label: 'Global Model', icon: Brain },
    { id: 'performance', label: 'Performance', icon: Gauge }, { id: 'users', label: 'Users', icon: Users }, { id: 'settings', label: 'Settings', icon: Settings },
  ]
  return <aside className={cn('fixed inset-y-0 left-0 z-30 flex w-60 -translate-x-full flex-col bg-foreground px-3 py-5 text-background transition-transform md:sticky md:translate-x-0', open && 'translate-x-0')}>
    <div className="flex items-center gap-3 px-2 pb-7"><div className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><HeartPulse className="size-5" /></div><div><p className="text-sm font-bold">Heart Disease</p><p className="text-xs text-background/65">FL System</p></div><Button variant="ghost" size="icon" className="ml-auto text-background md:hidden" aria-label="Close menu" onClick={() => setOpen(false)}><X /></Button></div>
    <nav className="grid gap-1">{navItems.map(({ id, label, icon: Icon }) => <Button key={id} variant="ghost" onClick={() => { setPage(id); setOpen(false) }} className={cn('justify-start gap-3 text-background/75 hover:bg-background/15 hover:text-background', (page === id || page.startsWith(`${id}:`)) && 'bg-background/15 text-background')}><Icon className="size-4" />{label}</Button>)}</nav>
    <Button variant="ghost" onClick={() => onNotice('Demo logout action')} className="mt-auto justify-start gap-3 text-background/75 hover:bg-background/15 hover:text-background"><LogOut className="size-4" />Logout</Button>
  </aside>
}

function Header({ page, setOpen, onNotice }: { page: Page; setOpen: (open: boolean) => void; onNotice: (message: string) => void }) {
  const titles: Record<Exclude<Page, `hospitals:${string}`>, string> = { dashboard: 'Admin Dashboard', hospitals: 'Hospitals', monitoring: 'FL Monitoring', model: 'Global Model', performance: 'Performance', users: 'Users', settings: 'Settings' }
  const title = page.startsWith('hospitals:') ? 'Hospital Details' : titles[page as Exclude<Page, `hospitals:${string}`>]
  return <header className="flex min-h-20 items-center justify-between border-b bg-card px-4 md:px-7"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" aria-label="Open menu" className="md:hidden" onClick={() => setOpen(true)}><Menu /></Button><div><p className="text-[10px] font-medium tracking-widest text-muted-foreground">HEALTHCARE AI PLATFORM</p><h1 className="mt-1 text-xl font-bold">{title}</h1><p className="mt-1 text-xs text-muted-foreground">Overview of Federated Learning System</p></div></div><div className="flex items-center gap-3"><Button variant="ghost" size="icon" aria-label="Check notifications" onClick={() => onNotice('No new notifications')}><Bell className="size-5" /></Button><div className="grid size-9 place-items-center rounded-full bg-primary/15 font-bold text-primary">A</div><div className="hidden sm:block"><p className="text-xs font-semibold">Admin</p><p className="text-xs text-muted-foreground">Super Admin</p></div></div></header>
}

function Intro({ title, sub, action, onAction, back }: { title: string; sub: string; action?: string; onAction?: () => void; back?: () => void }) { return <div className="mb-5 flex items-start justify-between gap-4"><div>{back && <Button variant="link" onClick={back} className="mb-1 h-auto gap-1 px-0 text-xs"><ArrowLeft className="size-3.5" />Back</Button>}<h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{sub}</p></div>{action && onAction && <Button onClick={onAction}>{action}</Button>}</div> }

function Stat({ icon: Icon, label, value, note, tone = 'default', onClick }: { icon: ComponentType<{ className?: string }>; label: string; value: string | number; note: string; tone?: Tone; onClick?: () => void }) {
  const tones: Record<Tone, string> = { default: 'bg-primary/15 text-primary', blue: 'bg-chart-1/15 text-chart-1', green: 'bg-success/15 text-success', orange: 'bg-warning/15 text-warning' }
  const content = <><span className={cn('grid size-11 shrink-0 place-items-center rounded-full', tones[tone])}><Icon className="size-5" /></span><span className="min-w-0 text-left"><span className="block text-xs text-muted-foreground">{label}</span><strong className="my-1 block text-xl">{value}</strong><span className="block text-xs text-success">{note}</span></span>{onClick && <ChevronRight className="ml-auto size-4 text-muted-foreground" />}</>
  return onClick ? <Button variant="outline" onClick={onClick} className="h-auto min-h-28 justify-start p-4 shadow-sm hover:border-primary">{content}</Button> : <Card className="min-h-28 shadow-sm"><CardContent className="flex items-center gap-3 p-4">{content}</CardContent></Card>
}

function Workflow({ progress = 76 }: { progress?: number }) {
  const steps: { title: string; status: string; tone: string; icon: ComponentType<{ className?: string }> }[] = [{ title: 'Local Training', status: 'Completed', tone: 'bg-success', icon: Activity }, { title: 'Model Update', status: 'Ready', tone: 'bg-chart-1', icon: Upload }, { title: 'FedAvg', status: 'In Progress', tone: 'bg-primary', icon: Network }, { title: 'Global Model', status: 'Updated', tone: 'bg-success', icon: Brain }]
  return <div><div className="flex min-w-max items-start justify-between gap-2 overflow-x-auto py-4">{steps.map(({ title, status, tone, icon: Icon }, index) => <div key={title} className="flex items-start gap-2"><div className="w-20 text-center"><span className={cn('mx-auto mb-2 grid size-9 place-items-center rounded-full text-primary-foreground', tone)}><Icon className="size-4" /></span><strong className="block text-[11px]">{title}</strong><span className="mt-1 block text-[10px] text-muted-foreground">Federated process</span><em className="mt-1 block text-[10px] not-italic font-semibold text-primary">{status}</em></div>{index < steps.length - 1 && <ChevronRight className="mt-3 size-4 text-muted-foreground" />}</div>)}</div><div className="mt-2"><div className="mb-2 flex justify-between text-xs"><b>Round 12 in progress</b><b>{progress}%</b></div><Progress value={progress} /></div></div>
}

function HospitalTable({ setPage }: { setPage: (page: Page) => void }) { return <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Hospital ID</TableHead><TableHead>Hospital</TableHead><TableHead>Status</TableHead><TableHead>Last Update</TableHead><TableHead>Round</TableHead><TableHead><span className="sr-only">View</span></TableHead></TableRow></TableHeader><TableBody>{hospitals.map((hospital) => <TableRow key={hospital.id}><TableCell className="font-semibold">{hospital.id}</TableCell><TableCell>{hospital.name}</TableCell><TableCell><StatusBadge status={hospital.status} /></TableCell><TableCell>{hospital.update}</TableCell><TableCell>{hospital.round}</TableCell><TableCell><Button variant="secondary" size="sm" onClick={() => setPage(`hospitals:${hospital.id}`)}>View <ChevronRight className="size-3" /></Button></TableCell></TableRow>)}</TableBody></Table></div> }

function Panel({ title, subtitle, action, children }: { title: string; subtitle?: string; action?: { label: string; onClick: () => void }; children: React.ReactNode }) { return <Card className="shadow-sm"><CardHeader className="flex flex-row items-start justify-between space-y-0 pb-3"><div><CardTitle className="text-sm">{title}</CardTitle>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action && <Button variant="link" size="sm" className="h-auto px-0" onClick={action.onClick}>{action.label}</Button>}</CardHeader><CardContent>{children}</CardContent></Card> }

function PerformanceOverview() { const metrics = [['Accuracy', '92.4%'], ['Precision', '90.8%'], ['Recall', '91.6%'], ['F1-Score', '90.2%']]; return <><div className="mx-auto grid size-28 place-items-center rounded-full bg-[conic-gradient(hsl(var(--chart-1))_0_32%,hsl(var(--primary))_32%_67%,hsl(var(--success))_67%_82%,hsl(var(--muted))_82%)]"><div className="grid size-20 place-items-center rounded-full bg-card text-center"><strong>92.4%</strong><span className="text-[10px] text-muted-foreground">Accuracy</span></div></div><div className="mt-5 grid gap-2 text-xs text-muted-foreground">{metrics.map(([label, value]) => <div key={label} className="flex justify-between"><span>{label}</span><b className="text-foreground">{value}</b></div>)}</div></> }

function Info({ rows }: { rows: [string, string | number][] }) { return <div className="divide-y">{rows.map(([label, value]) => <div key={label} className="flex justify-between gap-4 py-3 text-sm"><span className="text-muted-foreground">{label}</span><b className="text-right">{value}</b></div>)}</div> }

function Dashboard({ setPage, onNotice }: { setPage: (page: Page) => void; onNotice: (message: string) => void }) { return <><Intro title="Admin Dashboard" sub="Overview of Federated Learning System." /><div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Building2} label="Total Hospitals" value="18" note="+2 this month" onClick={() => setPage('hospitals')} /><Stat icon={Users} label="Active Clients" value="15" note="● Online" tone="blue" onClick={() => setPage('users')} /><Stat icon={Network} label="Current FL Round" value="12" note="In Progress" onClick={() => setPage('monitoring')} /><Stat icon={ShieldCheck} label="Global Model Status" value="Updated" note="2 min ago" tone="green" onClick={() => setPage('model')} /></div><div className="mb-4 grid gap-3 xl:grid-cols-[1fr_1.2fr_.82fr]"><Panel title="Hospital Status" subtitle="Participating clients" action={{ label: 'View all', onClick: () => setPage('hospitals') }}><HospitalTable setPage={setPage} /></Panel><Panel title="Federated Learning Process" subtitle="Current global round" action={{ label: 'Monitor', onClick: () => setPage('monitoring') }}><Workflow /></Panel><Panel title="Performance Overview" subtitle="Global model" action={{ label: 'Details', onClick: () => setPage('performance') }}><PerformanceOverview /></Panel></div><Panel title="System Notifications" subtitle="Latest activity" action={{ label: 'Refresh', onClick: () => onNotice('Notifications refreshed') }}><div className="flex items-center gap-2 rounded-md bg-success/10 p-3 text-sm text-success"><CheckCircle2 className="size-4 shrink-0" /><span>Round 12 aggregation completed from 10 hospitals.</span><small className="ml-auto whitespace-nowrap text-muted-foreground">2 min ago</small></div></Panel></> }

function Hospitals({ setPage, onNotice }: { setPage: (page: Page) => void; onNotice: (message: string) => void }) { return <><Intro title="Hospitals" sub="Manage and monitor each participating hospital." action="+ Add Hospital" onAction={() => onNotice('Add Hospital demo action')} /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{hospitals.map((hospital) => <Button key={hospital.id} variant="outline" onClick={() => setPage(`hospitals:${hospital.id}`)} className="relative h-auto min-h-44 justify-start whitespace-normal p-4 text-left shadow-sm hover:border-primary"><div className="grid size-11 place-items-center rounded-lg bg-chart-1/15 text-chart-1"><Building2 /></div><div className="ml-3"><p className="text-xs text-muted-foreground">{hospital.id}</p><h3 className="mt-1 text-sm font-semibold">{hospital.name}</h3><StatusBadge status={hospital.status} /></div><ChevronRight className="absolute right-4 top-5 size-4 text-muted-foreground" /><div className="absolute inset-x-4 bottom-4 flex gap-8 border-t pt-3 text-xs text-muted-foreground"><span>Round <b className="ml-1 text-foreground">{hospital.round}</b></span><span>Records <b className="ml-1 text-foreground">{hospital.records}</b></span></div></Button>)}</div></> }

function ActivityList() { return <div className="grid gap-2">{[[CheckCircle2, 'Global model received', 'Round 11 • 2 min ago'], [Upload, 'Model update prepared', 'Round 12 • 4 min ago'], [Activity, 'Local training started', 'Round 12 • 8 min ago']].map(([Icon, title, note]) => { const ItemIcon = Icon as ComponentType<{ className?: string }>; return <div key={title as string} className="flex items-center gap-3 rounded-md bg-muted/60 p-3"><ItemIcon className="size-4 text-primary" /><span><b className="block text-xs">{title as string}</b><small className="text-xs text-muted-foreground">{note as string}</small></span></div> })}</div> }

function HospitalDetails({ id, setPage, onNotice }: { id: string; setPage: (page: Page) => void; onNotice: (message: string) => void }) { const hospital = hospitals.find((item) => item.id === id) ?? hospitals[0]!; return <><Intro back={() => setPage('hospitals')} title={hospital.name} sub={`${hospital.id} • Individual Hospital Details`} /><div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Building2} label="Hospital ID" value={hospital.id} note={hospital.name} /><Stat icon={Network} label="Current FL Round" value={hospital.round} note="Active" tone="blue" /><Stat icon={Activity} label="Training Status" value={hospital.status} note={`${hospital.progress}% progress`} tone="orange" /><Stat icon={Brain} label="Global Model" value="v2.1.0" note="Updated 2 min ago" tone="green" /></div><div className="mb-4 grid gap-3 xl:grid-cols-[1.25fr_.75fr]"><Panel title="Federated Learning Workflow" subtitle={`${hospital.id} current round`} action={{ label: 'Restart', onClick: () => onNotice(`Training restarted for ${hospital.id}`) }}><Workflow progress={hospital.progress || 65} /></Panel><Panel title="Hospital Information" subtitle="Client details"><Info rows={[["Hospital ID", hospital.id], ['Patient records', hospital.records], ['Current round', hospital.round], ['Last update', hospital.update], ['Privacy status', 'Protected']]} /></Panel></div><Panel title="Training Activity" subtitle="Recent events" action={{ label: 'Refresh', onClick: () => onNotice('Activity refreshed') }}><ActivityList /></Panel></> }

function Generic({ page, setPage, onNotice }: { page: Exclude<Page, 'dashboard' | 'hospitals' | `hospitals:${string}`>; setPage: (page: Page) => void; onNotice: (message: string) => void }) { const content: Record<typeof page, [string, string]> = { monitoring: ['FL Monitoring', 'Monitor every federated learning round and client status.'], model: ['Global Model', 'Global model versions, aggregation and deployment status.'], performance: ['Performance', 'Global model evaluation metrics.'], users: ['Users', 'Manage platform users and roles.'], settings: ['Settings', 'Configure admin dashboard preferences.'] }; const [title, sub] = content[page]; if (page === 'performance') return <><Intro title={title} sub={sub} /><div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Gauge} label="Accuracy" value="92.4%" note="Latest global model" /><Stat icon={Activity} label="Precision" value="90.8%" note="Latest global model" tone="blue" /><Stat icon={HeartPulse} label="Recall" value="91.6%" note="Latest global model" /><Stat icon={Brain} label="F1-Score" value="90.2%" note="Latest global model" tone="green" /></div><Panel title="Metric Comparison"><MetricChart /></Panel></>; if (page === 'monitoring') return <><Intro title={title} sub={sub} /><Panel title="Federated Learning Round 12"><Workflow progress={76} /><div className="mt-4"><HospitalTable setPage={setPage} /></div></Panel></>; if (page === 'model') return <><Intro title={title} sub={sub} /><Panel title="Global Model Status"><div className="mb-4 flex items-center gap-3 rounded-lg bg-success/10 p-5 text-success"><CheckCircle2 className="size-7" /><strong className="text-lg">Updated</strong><span className="text-xs text-success/80">Version v2.1.0 • Round 12 • 2 min ago</span></div><Button onClick={() => onNotice('Model deployment demo action')}>Deploy Model</Button></Panel></>; if (page === 'users') return <><Intro title={title} sub={sub} /><Panel title="Platform Users"><div className="grid gap-2">{['Admin • Super Admin', 'Dr. Smith • HOSP-001', 'Hospital Admin • HOSP-002', 'Demo Patient • User'].map((user) => <div key={user} className="flex items-center gap-3 rounded-md border p-3"><Users className="size-4 text-primary" /><b className="text-sm">{user}</b><Button variant="secondary" size="sm" className="ml-auto" onClick={() => onNotice('User details demo')}>View</Button></div>)}</div></Panel></>; return <><Intro title={title} sub={sub} /><Panel title="Admin Settings"><Info rows={[["Auto refresh", 'Enabled'], ['Notifications', 'Enabled'], ['Theme', 'Light'], ['Federated privacy', 'Enabled']]} /><Button className="mt-4" onClick={() => onNotice('Settings saved')}>Save Settings</Button></Panel></> }

function MetricChart() { const data: [string, number][] = [['Accuracy', 92.4], ['Precision', 90.8], ['Recall', 91.6], ['F1-Score', 90.2]]; return <div className="grid gap-5 py-2">{data.map(([label, value]) => <div key={label} className="grid grid-cols-[75px_1fr_45px] items-center gap-3 text-xs"><span>{label}</span><Progress value={value} /><b className="text-right">{value}%</b></div>)}</div> }

export default function AdminDashboard() { const navigate = useNavigate(); const [page, setPage] = useState<Page>('dashboard'); const [menuOpen, setMenuOpen] = useState(false); const [notice, setNotice] = useState<string | null>(null); const view = useMemo(() => { if (page === 'dashboard') return <Dashboard setPage={setPage} onNotice={setNotice} />; if (page === 'hospitals') return <Hospitals setPage={setPage} onNotice={setNotice} />; if (page.startsWith('hospitals:')) return <HospitalDetails id={page.split(':')[1] ?? ''} setPage={setPage} onNotice={setNotice} />; return <Generic page={page as Exclude<Page, 'dashboard' | 'hospitals' | `hospitals:${string}`>} setPage={setPage} onNotice={setNotice} /> }, [page]); return <div className="flex min-h-screen bg-background text-foreground"><Sidebar page={page} setPage={setPage} open={menuOpen} setOpen={setMenuOpen} onNotice={() => navigate('/')} /><main className="min-w-0 flex-1"><Header page={page} setOpen={setMenuOpen} onNotice={setNotice} /><section className="mx-auto max-w-[1700px] p-4 md:p-7">{notice && <div className="mb-4 flex items-center justify-between rounded-md border bg-card px-3 py-2 text-sm shadow-sm"><span>{notice}</span><Button variant="ghost" size="icon" aria-label="Dismiss notification" onClick={() => setNotice(null)}><X className="size-4" /></Button></div>}{view}</section></main></div> }
